CREATE TABLE APP_USER 
(  
	USER_ID  integer ,
	EMAIL varchar(40) NOT NULL,   
	PASSWORD varchar(20), 
	FIRST_NAME varchar(20),
	MIDDLE_NAME varchar(20),
	LAST_NAME varchar(20),
	ZIP varchar(10),
	PROFILE_PIC_STORAGE_LOCATION TEXT,
	PRIMARY KEY (USER_ID)
--	UNIQUE KEY EMAIL (EMAIL)
) ;

CREATE TABLE PET 
(  
	PET_ID  integer ,
	PET_TYPE varchar(40) NOT NULL,   
	BREED varchar(20), 
	NAME varchar(20), 
	PREFERENCES TEXT, 
	USER_ID  integer NOT NULL,
	PRIMARY KEY (PET_ID),
	FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID)
) ;

CREATE TABLE POST 
(  
	POST_ID  integer ,
	POST_TEXT TEXT,   
	USER_ID  integer NOT NULL,
	CREATED_AT timestamp default current_timestamp,
	PRIMARY KEY (POST_ID),
	FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID)
) ;

CREATE TABLE USER_RELATION
(
	USER_ID integer not null,
	RELATION_ID integer not null,
	PRIMARY KEY (USER_ID,RELATION_ID),
	FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID),
	FOREIGN KEY (RELATION_ID) REFERENCES APP_USER (USER_ID)
) ;

CREATE TABLE FAVORITE 
(  
	POST_ID integer NOT null,   
	USER_ID  integer NOT null,
	CREATED_AT timestamp default current_timestamp,
	PRIMARY KEY (POST_ID,USER_ID),
	FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID),
	FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID)
) ;

CREATE TABLE POST_COMMENT 
(  
	COMMENT_ID integer NOT null,   
	POST_ID  integer NOT null,
	USER_ID  integer NOT null,
	CREATED_AT timestamp default current_timestamp,
	COMMENT TEXT,
	PRIMARY KEY (COMMENT_ID),
	FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID),
	FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID)
) ; 

CREATE TABLE PICTURES 
(  
	PIC_ID integer NOT null,   
	PET_ID integer ,
	USER_ID  integer NOT null,
	POST_ID  integer NOT null,
	CREATED_AT timestamp default current_timestamp,
	STORAGE_LOCATION TEXT,
	NAME VARCHAR(1000),
	PIC_TYPE VARCHAR(20),
	PIC_SIZE integer,
	USER_PROFILE_PIC BOOLEAN,
	PET_PROFILE_PIC BOOLEAN,
	PRIMARY KEY (PIC_ID),
	FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID),
	FOREIGN KEY (PET_ID) REFERENCES PET (PET_ID),
	FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID)
) ; 